from __future__ import annotations

from typing import Any, Protocol


class Repository(Protocol):
    def list_transactions(self) -> list[dict[str, Any]]: ...

    def create_transaction(self, payload: dict[str, Any], document_id: str | None = None) -> dict[str, Any]: ...

    def update_transaction(self, document_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete_transaction(self, document_id: str) -> bool: ...

    def create_conversation(self, title: str, messages: list[dict[str, Any]]) -> dict[str, Any]: ...

    def list_conversations(self) -> list[dict[str, Any]]: ...

    def get_conversation(self, document_id: str) -> dict[str, Any] | None: ...

    def append_conversation_messages(self, document_id: str, messages: list[dict[str, Any]]) -> dict[str, Any] | None: ...

    def delete_conversation(self, document_id: str) -> bool: ...

